using System;
using Content.Shared._Rat.SignalTransmitter;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Localization;

namespace Content.Client._Rat.SignalTransmitter;

[GenerateTypedNameReferences]
public sealed partial class TransmitterMenu : DefaultWindow
{
    public event Action<int>? OnKeypadButtonPressed;
    public event Action? OnClearButtonPressed;
    public event Action? OnEnterButtonPressed;

    public TransmitterMenu()
    {
        RobustXamlLoader.Load(this);
        FillKeypadGrid();
    }

    private void FillKeypadGrid()
    {
        for (var i = 1; i <= 9; i++)
        {
            AddKeypadButton(i);
        }

        var clearBtn = new Button { Text = "C" };
        clearBtn.OnPressed += _ => OnClearButtonPressed?.Invoke();
        KeypadGrid.AddChild(clearBtn);

        AddKeypadButton(0);

        var enterBtn = new Button { Text = "E" };
        enterBtn.OnPressed += _ => OnEnterButtonPressed?.Invoke();
        KeypadGrid.AddChild(enterBtn);
    }

    private void AddKeypadButton(int i)
    {
        var btn = new Button { Text = i.ToString() };
        btn.OnPressed += _ => OnKeypadButtonPressed?.Invoke(i);
        KeypadGrid.AddChild(btn);
    }

    public void UpdateState(SignalTransmitterUiState state)
    {
        if (state.Activated)
        {
            StatusLabel.Text = Loc.GetString("transmitter-ui-status-activated");
            CodeLabel.Text = Loc.GetString("transmitter-ui-code-accepted");
        }
        else
        {
            StatusLabel.Text = Loc.GetString("transmitter-ui-status-input-code");
            CodeLabel.Text = Loc.GetString("transmitter-ui-code-display",
                ("code", VisualizeCode(state.EnteredCodeLength, state.MaxCodeLength)));
        }
    }

    private string VisualizeCode(int codeLength, int maxLength)
    {
        var code = new string('*', codeLength);
        var blanks = new string('_', maxLength - codeLength);
        return code + blanks;
    }
}
