// Ratgore Start
using System.Globalization;
using System.Numerics;
using Content.Client.Stylesheets;
using Content.Client.UserInterface.Controls;
using Content.Shared._Rat.HardlinerFireControl;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Rat.HardlinerFireControl;

[GenerateTypedNameReferences]
public sealed partial class HardlinerFireControlMenu : FancyWindow
{
    public HardlinerFireControlMenu()
    {
        RobustXamlLoader.Load(this);
    }

    public void ApplyTelemetry(List<HardlinerTelemetryRowState> rows)
    {
        WeaponsColumn.RemoveAllChildren();

        if (rows.Count == 0)
        {
            WeaponsColumn.AddChild(new Label
            {
                Text = Loc.GetString("hardliner-fire-control-no-weapons"),
                FontColorOverride = Color.FromHex("#c4ccd6"),
                Margin = new Thickness(4, 12, 4, 4),
            });
            return;
        }

        foreach (var row in rows)
            WeaponsColumn.AddChild(BuildWeaponPanel(row));
    }

    private PanelContainer BuildWeaponPanel(HardlinerTelemetryRowState row)
    {
        var outer = new PanelContainer
        {
            Margin = new Thickness(0, 0, 0, 10),
        };
        outer.AddStyleClass("AngleRect");

        var root = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            Margin = new Thickness(12, 12, 12, 12),
        };

        outer.AddChild(root);

        root.AddChild(new Label
        {
            Text = Loc.GetString("hardliner-fire-control-address", ("address", row.DeviceAddress)),
            StyleClasses = { StyleNano.StyleClassLabelKeyText },
            FontColorOverride = Color.FromHex("#b8f7ff"),
        });

        var statusRow = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            Margin = new Thickness(0, 8, 0, 6),
        };

        statusRow.AddChild(StatusChip(
            row.GridPowered ? "hardliner-fire-control-grid-online" : "hardliner-fire-control-grid-offline",
            row.GridPowered ? "#143d28" : "#3d1414"));

        statusRow.AddChild(new PanelContainer { MinSize = new Vector2(8, 0) });

        statusRow.AddChild(StatusChip(
            row.Armed ? "hardliner-fire-control-armed" : "hardliner-fire-control-safe",
            row.Armed ? "#3d3014" : "#142b3d"));

        root.AddChild(statusRow);

        root.AddChild(SectionLabel("hardliner-fire-control-capacitor-header"));
        root.AddChild(MakeBarRow(row.CapacitorFraction, "#39ffc8"));

        root.AddChild(new Label
        {
            Text = Loc.GetString("hardliner-fire-control-capacitor-detail",
                ("current", row.CapacitorJoules),
                ("cost", row.ShotEnergyJoules)),
            StyleClasses = { StyleNano.StyleClassItemStatus },
            FontColorOverride = Color.FromHex("#c8d6df"),
            Margin = new Thickness(0, 4, 0, 10),
        });

        root.AddChild(SectionLabel("hardliner-fire-control-recycle-header"));
        root.AddChild(MakeBarRow(row.RecycleFraction, "#7eb8ff"));

        root.AddChild(SectionLabel("hardliner-fire-control-magazine-header"));

        root.AddChild(new Label
        {
            Text = Loc.GetString("hardliner-fire-control-magazine-count",
                ("current", row.ShotsRemaining),
                ("max", row.ShotsCapacity)),
            StyleClasses = { StyleNano.StyleClassLabelKeyText },
            FontColorOverride = Color.FromHex("#e6f2ff"),
            Margin = new Thickness(0, 2, 0, 4),
        });

        var magFrac = row.ShotsCapacity <= 0 ? 0f : row.ShotsRemaining / (float) row.ShotsCapacity;
        root.AddChild(MakeBarRow(magFrac, "#ffcf66"));

        return outer;
    }

    private static Label SectionLabel(string locId)
    {
        return new Label
        {
            Text = Loc.GetString(locId),
            StyleClasses = { StyleNano.StyleClassItemStatus },
            FontColorOverride = Color.FromHex("#8ea7bd"),
            Margin = new Thickness(0, 4, 0, 2),
        };
    }

    private static PanelContainer StatusChip(string locId, string backdropHex)
    {
        var panel = new PanelContainer();
        panel.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = Color.FromHex(backdropHex),
            BorderColor = Color.FromHex("#2b3540"),
            BorderThickness = new Thickness(1),
        };

        panel.AddChild(new Label
        {
            Text = Loc.GetString(locId),
            Margin = new Thickness(10, 4, 10, 4),
            FontColorOverride = Color.FromHex("#f5fbff"),
            StyleClasses = { StyleNano.StyleClassLabelSubText },
        });

        return panel;
    }

    private static BoxContainer MakeBarRow(float fraction, string accentHint)
    {
        fraction = Math.Clamp(fraction, 0f, 1f);

        var row = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalExpand = true,
            Margin = new Thickness(0, 0, 0, 4),
        };

        var bar = new ProgressBar
        {
            MinValue = 0,
            MaxValue = 1,
            Value = fraction,
            HorizontalExpand = true,
            MinHeight = 16,
        };

        bar.ForegroundStyleBoxOverride = new StyleBoxFlat
        {
            BackgroundColor = Color.FromHex(accentHint),
        };

        var pct = new Label
        {
            Text = (fraction * 100f).ToString("0", CultureInfo.InvariantCulture) + "%",
            Align = Label.AlignMode.Right,
            FontColorOverride = Color.FromHex("#dfeaf5"),
            StyleClasses = { StyleNano.StyleClassItemStatus },
            MinWidth = 52,
            Margin = new Thickness(8, 0, 0, 0),
        };

        row.AddChild(bar);
        row.AddChild(pct);

        return row;
    }
}
// Ratgore End
