using Content.Client.UserInterface.Controls;
using Content.Shared._Rat.LifeInsurance;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Rat.LifeInsurance;

[GenerateTypedNameReferences]
public sealed partial class LifeInsuranceWindow : FancyWindow
{
    /// <summary>Raw material units are shown in UI divided by this (matches exotic protein stack convention).</summary>
    private const int ProteinDisplayDivisor = 500;

    private readonly List<LifeInsuranceTargetEntry> _targets = new();
    private readonly List<int> _filteredIndices = new();
    private int? _selectedFilteredIndex;
    private int _requiredProteins;

    public event Action<NetEntity>? InsurePressed;
    public event Action<NetEntity>? VoidPressed;
    public event Action? EjectPressed;

    public LifeInsuranceWindow()
    {
        RobustXamlLoader.Load(this);
        Title = Loc.GetString("life-insurance-console-title");
        PlayersList.OnItemSelected += OnPlayerSelected;
        SearchLine.OnTextChanged += _ => RebuildList();
        InsureButton.OnPressed += _ => OnInsureButtonPressed();
        VoidButton.OnPressed += _ => OnVoidButtonPressed();
        EjectButton.OnPressed += _ => EjectPressed?.Invoke();
        SetDetails(null);
    }

    public void UpdateState(LifeInsuranceConsoleState state)
    {
        _targets.Clear();
        _targets.AddRange(state.Targets);
        _requiredProteins = state.RequiredProteins;

        ProteinsLabel.Text = Loc.GetString("life-insurance-stored-proteins",
            ("stored", state.StoredProteins / ProteinDisplayDivisor));

        RebuildList();
    }

    private void OnPlayerSelected(ItemList.ItemListSelectedEventArgs args)
    {
        if (args.ItemIndex < 0 || args.ItemIndex >= _filteredIndices.Count)
            return;

        _selectedFilteredIndex = args.ItemIndex;
        SetDetails(GetSelectedEntry());
    }

    private void OnInsureButtonPressed()
    {
        var target = GetSelectedEntry();
        if (target == null || target.AlreadyInsured || target.HasPendingRespawn)
            return;

        InsurePressed?.Invoke(target.Target);
    }

    private void OnVoidButtonPressed()
    {
        var target = GetSelectedEntry();
        if (target == null || (!target.AlreadyInsured && !target.HasPendingRespawn))
            return;

        VoidPressed?.Invoke(target.Target);
    }

    private LifeInsuranceTargetEntry? GetSelectedEntry()
    {
        if (_selectedFilteredIndex == null
            || _selectedFilteredIndex.Value < 0
            || _selectedFilteredIndex.Value >= _filteredIndices.Count)
            return null;

        return _targets[_filteredIndices[_selectedFilteredIndex.Value]];
    }

    private void RebuildList()
    {
        _filteredIndices.Clear();
        PlayersList.Clear();

        var filter = SearchLine.Text.Trim();
        for (var i = 0; i < _targets.Count; i++)
        {
            var entry = _targets[i];
            if (!string.IsNullOrWhiteSpace(filter)
                && !entry.Name.Contains(filter, StringComparison.OrdinalIgnoreCase)
                && !entry.RoleName.Contains(filter, StringComparison.OrdinalIgnoreCase))
                continue;

            _filteredIndices.Add(i);
            string status;
            if (entry.AlreadyInsured)
                status = Loc.GetString("life-insurance-list-status-insured");
            else if (entry.HasPendingRespawn)
                status = Loc.GetString("life-insurance-list-status-pending");
            else
                status = Loc.GetString("life-insurance-list-status-not-insured");
            PlayersList.AddItem($"{entry.Name} — {entry.RoleName} ({status})");
        }

        if (_filteredIndices.Count == 0)
        {
            _selectedFilteredIndex = null;
            SetDetails(null);
            return;
        }

        if (_selectedFilteredIndex == null || _selectedFilteredIndex.Value >= _filteredIndices.Count)
            _selectedFilteredIndex = 0;

        SetDetails(GetSelectedEntry());
    }

    private void SetDetails(LifeInsuranceTargetEntry? entry)
    {
        if (entry == null)
        {
            DetailsName.Text = Loc.GetString("life-insurance-no-selection");
            DetailsRole.Text = string.Empty;
            DetailsStatus.Text = string.Empty;
            DetailsStatus.FontColorOverride = null;
            ClearQuoteBox();
            InsureButton.Disabled = true;
            VoidButton.Disabled = true;
            return;
        }

        DetailsName.Text = Loc.GetString("life-insurance-details-name", ("name", entry.Name));
        DetailsRole.Text = Loc.GetString("life-insurance-details-role", ("role", entry.RoleName));

        string statusText;
        Color statusColor;
        if (entry.AlreadyInsured)
        {
            statusText = Loc.GetString("life-insurance-details-status-insured");
            statusColor = Color.FromHex("#4CAF50");
        }
        else if (entry.HasPendingRespawn)
        {
            statusText = Loc.GetString("life-insurance-details-status-pending");
            statusColor = Color.FromHex("#FFA726");
        }
        else
        {
            statusText = Loc.GetString("life-insurance-details-status-not-insured");
            statusColor = Color.FromHex("#9E9E9E");
        }

        DetailsStatus.Text = statusText;
        DetailsStatus.FontColorOverride = statusColor;

        if (!entry.AlreadyInsured && !entry.HasPendingRespawn)
        {
            DetailsQuoteText.Visible = true;
            DetailsQuoteText.Text = Loc.GetString("life-insurance-details-quote",
                ("proteins", _requiredProteins / ProteinDisplayDivisor),
                ("credits", entry.NextCreditsPrice));
        }
        else
        {
            ClearQuoteBox();
        }

        InsureButton.Disabled = entry.AlreadyInsured || entry.HasPendingRespawn;
        VoidButton.Disabled = !(entry.AlreadyInsured || entry.HasPendingRespawn);
    }

    private void ClearQuoteBox()
    {
        DetailsQuoteText.Visible = false;
        DetailsQuoteText.Text = string.Empty;
    }
}
